/**
 * The rendering budget and the colour-separation bound, recomputed.
 *
 * Two round-2 defects motivated this file, and both share a shape: a table that
 * looked like arithmetic and was never run.
 *
 *   1. docs/DESIGN.md §7.1 computed every GPU pass in CSS-logical pixels. GPUs
 *      shade device pixels, and the three named reference devices run at DPR 2,
 *      2.6 and ~2.75, so the published load was understated by a factor of four
 *      to nine. The conclusion held; the figures did not.
 *   2. §15 prescribed two replacement sphere hexes to repair colour-blind
 *      separation. Both *reduced* the luminance separation of the pair they
 *      were prescribed to repair — #3D8BFF against VIOLET is 1.05:1, down from
 *      1.24:1. The instruction to "re-check every ratio" was an admission the
 *      check had never been run, and a named hex in a production spec gets
 *      actioned by whoever picks up the ticket.
 *
 * So: the pass table is generated by `tools/lib/framebudget.mjs` and asserted
 * against the document here, and the colour claim is replaced by a bound this
 * file proves — under a 4.5:1 floor against `--void`, seven colours cannot be
 * separated by luminance, whatever hexes anyone picks.
 */

import { readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { describe, expect, it } from 'vitest';

import {
  BACKING_STORE_DPR_CAP,
  CHAMBER_CSS,
  REFERENCE_DEVICES,
  clipExportBudget,
  frameBudget,
} from '../tools/lib/framebudget.mjs';
import { ELEMENTS } from '../tools/lib/model.mjs';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const DESIGN = readFileSync(join(ROOT, 'docs/DESIGN.md'), 'utf8');

const capped = frameBudget({ devicePixelRatio: 2 });

/* ------------------------------------------------------------------ *
 * 1. The frame budget is device pixels, and the document says so.      *
 * ------------------------------------------------------------------ */

describe('docs/DESIGN.md §7.1 states the budget in device pixels', () => {
  it('names the device-pixel ratio it was computed at', () => {
    expect(DESIGN).toMatch(/device[- ]pixel ratio/iu);
    expect(DESIGN).toContain('DPR');
  });

  it('states the backing-store cap as an art-direction decision, not a renderer detail', () => {
    expect(DESIGN).toContain(`capped at DPR ${BACKING_STORE_DPR_CAP}`);
    // The cap belongs where a designer will read it, next to the materials.
    const art = DESIGN.slice(DESIGN.indexOf('### 6.2 Materials'), DESIGN.indexOf('### 6.3 Lighting'));
    expect(art).toContain('backing store');
  });

  it('quotes the totals this module computes', () => {
    expect(DESIGN).toContain(`${capped.backing}`);
    expect(DESIGN).toContain(capped.shadedFragments.toLocaleString('en-US'));
    expect(DESIGN).toContain(`${capped.megafragmentsPerSecond.toFixed(1)} Mfrag/s`);
    expect(DESIGN).toContain(`${Math.round(capped.writeMegabytesPerSecond)} MB/s`);
    expect(DESIGN).toContain(`${Math.round(capped.trafficMegabytesPerSecond).toLocaleString('en-US')} MB/s`);
  });

  it('quotes every pass row', () => {
    for (const row of capped.rows) {
      expect(DESIGN, `pass ${row.id} resolution`).toContain(row.resolution);
      expect(DESIGN, `pass ${row.id} shaded fragments`).toContain(row.shadedFragments.toLocaleString('en-US'));
    }
  });

  it('quotes the uncapped figure for the highest-DPR reference device', () => {
    const worst = REFERENCE_DEVICES.reduce((a, b) => (b.devicePixelRatio > a.devicePixelRatio ? b : a));
    const uncapped = frameBudget({ devicePixelRatio: worst.devicePixelRatio, dprCap: null });
    expect(DESIGN).toContain(`${uncapped.megafragmentsPerSecond.toFixed(1)} Mfrag/s`);
  });

  it('the clip export cost is the one this module computes', () => {
    const clip = clipExportBudget();
    expect(DESIGN).toContain(`${clip.megafragmentsPerFrame.toFixed(2)} Mfrag/frame`);
    expect(DESIGN).toContain(`${Math.round(clip.totalMegafragments)} Mfrag`);
    // The stale figure counted only the composite pass.
    expect(DESIGN).not.toContain('2.07 Mfrag/frame');
  });

  it('no longer publishes the logical-pixel totals as the budget', () => {
    // The section names the old figures when explaining the defect; what it may
    // not do is present them in the table as the answer.
    const table = DESIGN.slice(DESIGN.indexOf('| # | Pass | Resolution (device px)'), DESIGN.indexOf('Bandwidth, at 4 bytes'));
    expect(table).not.toContain('20.6 Mfrag/s');
    expect(table).not.toContain('logical');
    expect(table).toContain(`${capped.megafragmentsPerSecond.toFixed(1)} Mfrag/s`);
  });
});

describe('the budget model behaves', () => {
  it('caps the backing store on every reference device above the cap', () => {
    for (const device of REFERENCE_DEVICES) {
      const budget = frameBudget({ devicePixelRatio: device.devicePixelRatio });
      expect(budget.effectiveDpr).toBe(Math.min(device.devicePixelRatio, BACKING_STORE_DPR_CAP));
      expect(budget.capped).toBe(device.devicePixelRatio > BACKING_STORE_DPR_CAP);
      // Capping means every device pays the same chamber cost.
      expect(budget.shadedFragments).toBe(capped.shadedFragments);
    }
  });

  it('scales quadratically with the ratio when uncapped', () => {
    const one = frameBudget({ devicePixelRatio: 1, dprCap: null });
    const two = frameBudget({ devicePixelRatio: 2, dprCap: null });
    expect(two.shadedFragments / one.shadedFragments).toBeCloseTo(4, 1);
  });

  it('the composite pass is the only full-resolution one', () => {
    const full = capped.rows.filter((row) => row.scale === 1);
    expect(full).toHaveLength(1);
    expect(full[0].targetPixels).toBe(CHAMBER_CSS.width * 2 * CHAMBER_CSS.height * 2);
  });

  it('stays far inside a mid-range part even uncapped at the worst reference ratio', () => {
    const worst = frameBudget({ devicePixelRatio: 3, dprCap: null });
    // 1 Gfrag/s is the low end of the named class; the budget must not need it.
    expect(worst.megafragmentsPerSecond).toBeLessThan(500);
    // 10 GB/s is the low end of the named memory bandwidth.
    expect(worst.trafficMegabytesPerSecond).toBeLessThan(5000);
  });
});

/* ------------------------------------------------------------------ *
 * 2. Luminance cannot be the colour-blind channel. Proved.             *
 * ------------------------------------------------------------------ */

const channel = (value) => {
  const c = value / 255;
  return c <= 0.03928 ? c / 12.92 : ((c + 0.055) / 1.055) ** 2.4;
};
const luminance = (hex) => {
  const n = Number.parseInt(hex.slice(1), 16);
  return 0.2126 * channel((n >> 16) & 255) + 0.7152 * channel((n >> 8) & 255) + 0.0722 * channel(n & 255);
};
const contrast = (a, b) => {
  const [hi, lo] = [luminance(a), luminance(b)].sort((x, y) => y - x);
  return (hi + 0.05) / (lo + 0.05);
};

const VOID = '#05070C';
const FLOOR = 4.5;

describe('the SEVEN colour-separation question, answered arithmetically', () => {
  it('every sphere clears the foreground floor against the void', () => {
    for (const element of ELEMENTS) {
      expect(contrast(element.hex, VOID), element.id).toBeGreaterThanOrEqual(FLOOR);
    }
  });

  it('the floor bounds how far apart any two of seven colours can be in luminance', () => {
    // A colour at ratio >= 4.5:1 against the void has (L + 0.05) >= 4.5 * (Lv + 0.05).
    // The brightest possible colour is white, at (1 + 0.05). So the whole set
    // lives inside a contrast span of:
    const span = 1.05 / (FLOOR * (luminance(VOID) + 0.05));
    expect(span).toBeCloseTo(4.478, 2);
    // Spread k colours geometrically across that span and the closest adjacent
    // pair is span^(1/(k-1)). This is an upper bound on the best achievable
    // minimum separation, attained only by a set that includes pure white and
    // sits exactly on the floor — which leaves no freedom for hue at all.
    const bestPossibleSeven = span ** (1 / 6);
    expect(bestPossibleSeven).toBeCloseTo(1.284, 2);
    expect(bestPossibleSeven).toBeLessThan(1.5);
    expect(DESIGN).toContain('1.28:1');
  });

  it('names the genuinely closest pair rather than the closest SEVEN-only pair', () => {
    const pairs = [];
    for (let i = 0; i < ELEMENTS.length; i += 1) {
      for (let j = i + 1; j < ELEMENTS.length; j += 1) {
        pairs.push({ a: ELEMENTS[i], b: ELEMENTS[j], ratio: contrast(ELEMENTS[i].hex, ELEMENTS[j].hex) });
      }
    }
    pairs.sort((x, y) => x.ratio - y.ratio);
    // Round 2 named INDIGO/VIOLET as the weakest pair. It is fourth: two pairs
    // inside the CLASSIC five are closer, so the problem is not a SEVEN problem.
    expect(pairs[0].a.id).toBe('amber');
    expect(pairs[0].b.id).toBe('aqua');
    expect(pairs[0].ratio.toFixed(2)).toBe('1.10');
    expect(DESIGN).toContain('AMBER↔AQUA at 1.10:1');
    expect(DESIGN).toContain('CORAL↔VIOLET at 1.14:1');
    expect(DESIGN).toContain('INDIGO↔VIOLET at 1.24:1');
    expect(DESIGN).toContain('ROSE↔CORAL at 1.34:1');
  });

  it('the withdrawn remedies really did make both pairs worse', () => {
    const byId = Object.fromEntries(ELEMENTS.map((element) => [element.id, element.hex]));
    expect(contrast('#3D8BFF', byId.violet)).toBeLessThan(contrast(byId.indigo, byId.violet));
    expect(contrast('#FF6FB0', byId.coral)).toBeLessThan(contrast(byId.rose, byId.coral));
    // They may be named where they are withdrawn; they may not be prescribed.
    expect(DESIGN).toMatch(/colour remedy is withdrawn/u);
    expect(DESIGN).not.toMatch(/move ROSE toward/u);
    // And they are not in the shipped palette.
    for (const element of ELEMENTS) {
      expect(element.hex).not.toBe('#3D8BFF');
      expect(element.hex).not.toBe('#FF6FB0');
    }
  });

  it('the document commits to the glyph as the guaranteed channel', () => {
    expect(DESIGN).toMatch(/the glyph is the\s+colour-blind channel/u);
    // Every element must carry a distinct glyph for that to be true.
    const glyphs = new Set(ELEMENTS.map((element) => element.glyph));
    expect(glyphs.size).toBe(ELEMENTS.length);
    for (const element of ELEMENTS) expect(DESIGN, element.glyph).toContain(element.glyph);
  });
});
