/**
 * The rendering budget and the colour-separation bound, recomputed.
 *
 * Two round-2 defects motivated this file, and both share a shape: a table that
 * looked like arithmetic and was never run.
 *
 *   1. docs/DESIGN.md §7.1 computed every GPU pass in CSS-logical pixels. GPUs
 *      shade device pixels, and the three named reference devices run at DPR 2,
 *      2.6 and ~2.75, so the published load was understated by a factor of four
 *      to nine. The conclusion held; the figures did not.
 *   2. §15 prescribed two replacement sphere hexes to repair colour-blind
 *      separation. Both *reduced* the luminance separation of the pair they
 *      were prescribed to repair — #3D8BFF against VIOLET is 1.05:1, down from
 *      1.24:1. The instruction to "re-check every ratio" was an admission the
 *      check had never been run, and a named hex in a production spec gets
 *      actioned by whoever picks up the ticket.
 *
 * So: the pass table is generated by `tools/lib/framebudget.mjs` and asserted
 * against the document here, and the colour claim is replaced by a bound this
 * file proves — under a 4.5:1 floor against `--void`, seven colours cannot be
 * separated by luminance, whatever hexes anyone picks.
 *
 * Round 4 then added a third of the same shape, one layer up: §6.1's "closest
 * pairs" list was typed by hand, every ratio in it was correct, and the SET was
 * wrong — it omitted AMBER↔ROSE (third) and published the fifth-closest. The
 * test below it sorted all 21 pairs and asserted only `pairs[0]` and four
 * substring matches, so it checked the numbers and never the claim. The list is
 * now generated by `tools/lib/palette.mjs` and the claim itself is asserted:
 * the published rows ARE the k closest pairs, in order.
 */

import { readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { describe, expect, it } from 'vitest';

import {
  BACKING_STORE_DPR_CAP,
  CHAMBER_CSS,
  CHROME_CSS,
  MAX_TICKET_ROWS,
  MOTION_MS,
  REFERENCE_DEVICES,
  chromeBudget,
  clipExportBudget,
  deviceFrameBudget,
  frameBudget,
} from '../tools/lib/framebudget.mjs';
import { ELEMENTS } from '../tools/lib/model.mjs';
import {
  PUBLISHED_CLOSEST_PAIRS,
  bestAchievableSeparation,
  closestPairs,
  closestPairsMarkdown,
  luminanceSpan,
  ratioText,
  spherePairs,
} from '../tools/lib/palette.mjs';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const DESIGN = readFileSync(join(ROOT, 'docs/DESIGN.md'), 'utf8');

/** Parse the §6.1 closest-pairs table out of the document. */
function documentedClosestPairs() {
  const start = DESIGN.indexOf('<!-- palette:closest-pairs:start -->');
  const end = DESIGN.indexOf('<!-- palette:closest-pairs:end -->');
  expect(start, 'docs/DESIGN.md is missing the closest-pairs markers').toBeGreaterThan(-1);
  expect(end).toBeGreaterThan(start);
  const rows = [];
  for (const line of DESIGN.slice(start, end).split('\n')) {
    const match = line.match(/^\|\s*(\d+)\s*\|\s*([A-Z]+↔[A-Z]+)\s*\|\s*(\d+\.\d{2}:1)\s*\|\s*(yes|no)\s*\|/u);
    if (match) rows.push({ rank: Number(match[1]), pair: match[2], ratio: match[3], inClassic: match[4] === 'yes' });
  }
  return rows;
}

const capped = frameBudget({ devicePixelRatio: 2 });

/* ------------------------------------------------------------------ *
 * 1. The frame budget is device pixels, and the document says so.      *
 * ------------------------------------------------------------------ */

describe('docs/DESIGN.md §7.1 states the budget in device pixels', () => {
  it('names the device-pixel ratio it was computed at', () => {
    expect(DESIGN).toMatch(/device[- ]pixel ratio/iu);
    expect(DESIGN).toContain('DPR');
  });

  it('states the backing-store cap as an art-direction decision, not a renderer detail', () => {
    expect(DESIGN).toContain(`capped at DPR ${BACKING_STORE_DPR_CAP}`);
    // The cap belongs where a designer will read it, next to the materials.
    const art = DESIGN.slice(DESIGN.indexOf('### 6.2 Materials'), DESIGN.indexOf('### 6.3 Lighting'));
    expect(art).toContain('backing store');
  });

  it('quotes the totals this module computes', () => {
    expect(DESIGN).toContain(`${capped.backing}`);
    expect(DESIGN).toContain(capped.shadedFragments.toLocaleString('en-US'));
    expect(DESIGN).toContain(`${capped.megafragmentsPerSecond.toFixed(1)} Mfrag/s`);
    expect(DESIGN).toContain(`${Math.round(capped.writeMegabytesPerSecond)} MB/s`);
    expect(DESIGN).toContain(`${Math.round(capped.trafficMegabytesPerSecond).toLocaleString('en-US')} MB/s`);
  });

  it('quotes every pass row', () => {
    for (const row of capped.rows) {
      expect(DESIGN, `pass ${row.id} resolution`).toContain(row.resolution);
      expect(DESIGN, `pass ${row.id} shaded fragments`).toContain(row.shadedFragments.toLocaleString('en-US'));
    }
  });

  it('quotes the uncapped figure for the highest-DPR reference device', () => {
    const worst = REFERENCE_DEVICES.reduce((a, b) => (b.devicePixelRatio > a.devicePixelRatio ? b : a));
    const uncapped = frameBudget({ devicePixelRatio: worst.devicePixelRatio, dprCap: null });
    expect(DESIGN).toContain(`${uncapped.megafragmentsPerSecond.toFixed(1)} Mfrag/s`);
  });

  it('the clip export cost is the one this module computes, overlay included', () => {
    const clip = clipExportBudget();
    expect(DESIGN).toContain(`${clip.megafragmentsPerFrame.toFixed(2)} Mfrag/frame`);
    expect(DESIGN).toContain(`${Math.round(clip.totalMegafragments).toLocaleString('en-US')} Mfrag`);
    // Round 3 counted only the composite pass; round 4 counted every chamber
    // pass and still left out the overlay composited over it on every frame —
    // the same omission §7.1.1 fixes on device.
    expect(clip.overlayFragmentsPerFrame).toBe(1080 * 1920);
    expect(clip.shadedFragmentsPerFrame).toBe(clip.chamberFragmentsPerFrame + clip.overlayFragmentsPerFrame);
    expect(DESIGN).toContain(`${(clip.chamberFragmentsPerFrame / 1e6).toFixed(2)} Mfrag`);
    expect(DESIGN).not.toContain('2.07 Mfrag/frame');
    expect(DESIGN).not.toContain('3.68 Mfrag/frame');
  });

  it('no longer publishes the logical-pixel totals as the budget', () => {
    // The section names the old figures when explaining the defect; what it may
    // not do is present them in the table as the answer.
    const table = DESIGN.slice(DESIGN.indexOf('| # | Pass | Resolution (device px)'), DESIGN.indexOf('Bandwidth, at 4 bytes'));
    expect(table).not.toContain('20.6 Mfrag/s');
    expect(table).not.toContain('logical');
    expect(table).toContain(`${capped.megafragmentsPerSecond.toFixed(1)} Mfrag/s`);
  });
});

/* ------------------------------------------------------------------ *
 * 1b. The layer the canvas budget does not contain.                    *
 *                                                                      *
 * §6.2 caps the WebGL backing store at DPR 2 and pays for it by moving  *
 * every hard edge — text, slot rings, tube outline, specular line —     *
 * into DOM and SVG at native DPR. §6.4 then animates exactly that layer *
 * for the whole of SETTLE. Round 4's five-pass table budgeted the       *
 * canvas and nothing else, so it proved the cheap half of the frame and *
 * was silent on the half the design deliberately loaded with hard       *
 * edges — which is the standard 60 fps failure on this device class.    *
 * ------------------------------------------------------------------ */

/** Parse the §7.1.1 chrome-budget table out of the document. */
function documentedChromeBudget() {
  const start = DESIGN.indexOf('<!-- chrome-budget:start -->');
  const end = DESIGN.indexOf('<!-- chrome-budget:end -->');
  expect(start, 'docs/DESIGN.md is missing the chrome-budget markers').toBeGreaterThan(-1);
  expect(end).toBeGreaterThan(start);
  const rows = [];
  for (const line of DESIGN.slice(start, end).split('\n')) {
    const cells = line.split('|').map((cell) => cell.trim());
    if (cells.length === 8 && /^\d/u.test(cells[2])) {
      rows.push({ name: cells[1], dpr: Number(cells[2]), layer: cells[3], composite: cells[4], total: cells[5], traffic: cells[6] });
    }
  }
  return rows;
}

describe('docs/DESIGN.md §7.1.1 budgets the DOM/SVG chrome layer', () => {
  const documented = documentedChromeBudget();

  it('covers every reference device, at native DPR rather than the capped one', () => {
    expect(documented.map((row) => row.name)).toEqual(REFERENCE_DEVICES.map((device) => device.name));
    for (const [index, device] of REFERENCE_DEVICES.entries()) {
      expect(documented[index].dpr).toBe(device.devicePixelRatio);
      const chrome = chromeBudget({ devicePixelRatio: device.devicePixelRatio });
      // The chrome layer is NOT capped: that is the whole point of §6.2.
      expect(chrome.viewport).toBe(documented[index].layer);
    }
  });

  it.each(REFERENCE_DEVICES.map((device) => [device.name, device.devicePixelRatio]))(
    '%s: every published figure is the one the module computes',
    (name, dpr) => {
      const row = documented.find((candidate) => candidate.name === name);
      const budget = deviceFrameBudget({ devicePixelRatio: dpr });
      expect(row.composite).toBe(`${budget.chrome.compositeMegafragmentsPerSecond.toFixed(1)} Mfrag/s`);
      expect(row.total).toBe(`${budget.totalMegafragmentsPerSecond.toFixed(1)} Mfrag/s`);
      expect(row.traffic).toBe(`${Math.round(budget.totalTrafficMegabytesPerSecond).toLocaleString('en-US')} MB/s`);
    },
  );

  it('the worst reference device is the one whose figures the prose quotes', () => {
    const worst = REFERENCE_DEVICES.reduce((a, b) => (b.devicePixelRatio > a.devicePixelRatio ? b : a));
    const chrome = chromeBudget({ devicePixelRatio: worst.devicePixelRatio });
    expect(chrome.viewport).toBe('1073 × 2321');
    expect(DESIGN).toContain(chrome.layerCount.toString());
    expect(DESIGN).toContain(chrome.promotedPixels.toLocaleString('en-US'));
    expect(DESIGN).toContain(`${chrome.promotedLayerMegabytes.toFixed(2)} MB`);
    expect(DESIGN).toContain(`${chrome.naiveRasterMegapixelsPerSecond.toFixed(1)} Mpx/s`);
    expect(DESIGN).toContain(`${Math.round(chrome.naiveUploadMegabytesPerSecond)} MB/s of texture upload`);
  });

  it('states the compositor-only rule that makes the raster budget zero', () => {
    const chrome = chromeBudget({ devicePixelRatio: 2.75 });
    expect(chrome.rasterPixelsPerFrame).toBe(0);
    expect(chrome.naiveRasterPixelsPerFrame).toBeGreaterThan(0);
    // The rule has to be in the motion table AND in the budget, because a
    // motion designer reads one of those and a renderer engineer reads the
    // other, and the defect is one of them not knowing about the other.
    const motion = DESIGN.slice(DESIGN.indexOf('### 6.4 Motion language'), DESIGN.indexOf('### 6.5 Typography'));
    expect(motion).toMatch(/`transform` and `opacity` only/u);
    expect(motion).toMatch(/stroke-width/u);
    expect(DESIGN).toMatch(/During SETTLE the chrome layer animates `transform` and `opacity` only/u);
  });

  it('serialises the ring rebounds by arithmetic rather than by hope', () => {
    for (const variant of ['classic', 'seven']) {
      const chrome = chromeBudget({ devicePixelRatio: 2.75, variant });
      expect(MOTION_MS.lockRebound).toBeLessThan(MOTION_MS.settleStagger[variant]);
      expect(chrome.concurrentRingRebounds, variant).toBe(1);
    }
    // And the motion table the module mirrors must still say those numbers.
    expect(DESIGN).toContain('420 ms (CLASSIC) / 360 ms (SEVEN)');
    expect(DESIGN).toContain('| Lock rebound | 90 ms |');
  });

  it('stops presenting the canvas figure as the whole frame', () => {
    const section = DESIGN.slice(DESIGN.indexOf('### 7.1 The frame budget'), DESIGN.indexOf('### 7.2 What "the same round"'));
    expect(section).toMatch(/2–7% of fill and\s+4–10% of bandwidth for the canvas/u);
    expect(section).toMatch(/6–22% of\s+fill and 10–25% of bandwidth/u);
    // And 60 fps is a budgeted target with a named acceptance test, not a
    // measurement, because no client exists to have measured it.
    expect(DESIGN).toContain('### 7.4 The acceptance test for the frame rate');
    expect(DESIGN).toMatch(/None of it has been run, because there is no client/u);
    expect(DESIGN).toMatch(/\*\*Target:\*\* 60 fps/u);
  });

  it('the ticket-strip geometry it budgets is specified in S4', () => {
    const s4 = DESIGN.slice(DESIGN.indexOf('### S4 — ROUND'), DESIGN.indexOf('### S5 — RESULT'));
    expect(s4).toContain(`${CHROME_CSS.ticketRow.width} × ${CHROME_CSS.ticketRow.height}`);
    expect(s4).toContain(`${CHROME_CSS.hairline.width} × ${CHROME_CSS.hairline.height}`);
    expect(s4).toContain(`${MAX_TICKET_ROWS}-line`);
  });
});

describe('the budget model behaves', () => {
  it('caps the backing store on every reference device above the cap', () => {
    for (const device of REFERENCE_DEVICES) {
      const budget = frameBudget({ devicePixelRatio: device.devicePixelRatio });
      expect(budget.effectiveDpr).toBe(Math.min(device.devicePixelRatio, BACKING_STORE_DPR_CAP));
      expect(budget.capped).toBe(device.devicePixelRatio > BACKING_STORE_DPR_CAP);
      // Capping means every device pays the same chamber cost.
      expect(budget.shadedFragments).toBe(capped.shadedFragments);
    }
  });

  it('scales quadratically with the ratio when uncapped', () => {
    const one = frameBudget({ devicePixelRatio: 1, dprCap: null });
    const two = frameBudget({ devicePixelRatio: 2, dprCap: null });
    expect(two.shadedFragments / one.shadedFragments).toBeCloseTo(4, 1);
  });

  it('the composite pass is the only full-resolution one', () => {
    const full = capped.rows.filter((row) => row.scale === 1);
    expect(full).toHaveLength(1);
    expect(full[0].targetPixels).toBe(CHAMBER_CSS.width * 2 * CHAMBER_CSS.height * 2);
  });

  it('stays far inside a mid-range part even uncapped at the worst reference ratio', () => {
    const worst = frameBudget({ devicePixelRatio: 3, dprCap: null });
    // 1 Gfrag/s is the low end of the named class; the budget must not need it.
    expect(worst.megafragmentsPerSecond).toBeLessThan(500);
    // 10 GB/s is the low end of the named memory bandwidth.
    expect(worst.trafficMegabytesPerSecond).toBeLessThan(5000);
  });
});

/* ------------------------------------------------------------------ *
 * 2. Luminance cannot be the colour-blind channel. Proved.             *
 * ------------------------------------------------------------------ */

const channel = (value) => {
  const c = value / 255;
  return c <= 0.03928 ? c / 12.92 : ((c + 0.055) / 1.055) ** 2.4;
};
const luminance = (hex) => {
  const n = Number.parseInt(hex.slice(1), 16);
  return 0.2126 * channel((n >> 16) & 255) + 0.7152 * channel((n >> 8) & 255) + 0.0722 * channel(n & 255);
};
const contrast = (a, b) => {
  const [hi, lo] = [luminance(a), luminance(b)].sort((x, y) => y - x);
  return (hi + 0.05) / (lo + 0.05);
};

const VOID = '#05070C';
const FLOOR = 4.5;

describe('the SEVEN colour-separation question, answered arithmetically', () => {
  it('every sphere clears the foreground floor against the void', () => {
    for (const element of ELEMENTS) {
      expect(contrast(element.hex, VOID), element.id).toBeGreaterThanOrEqual(FLOOR);
    }
  });

  it('the floor bounds how far apart any two of seven colours can be in luminance', () => {
    // A colour at ratio >= 4.5:1 against the void has (L + 0.05) >= 4.5 * (Lv + 0.05).
    // The brightest possible colour is white, at (1 + 0.05). So the whole set
    // lives inside a contrast span of:
    const span = 1.05 / (FLOOR * (luminance(VOID) + 0.05));
    expect(span).toBeCloseTo(4.478, 2);
    // Spread k colours geometrically across that span and the closest adjacent
    // pair is span^(1/(k-1)). This is an upper bound on the best achievable
    // minimum separation, attained only by a set that includes pure white and
    // sits exactly on the floor — which leaves no freedom for hue at all.
    const bestPossibleSeven = span ** (1 / 6);
    expect(bestPossibleSeven).toBeCloseTo(1.284, 2);
    expect(bestPossibleSeven).toBeLessThan(1.5);
    expect(DESIGN).toContain('1.28:1');
  });

  it('recomputes the closest pair independently of the palette module', () => {
    // This file's own arithmetic, deliberately not tools/lib/palette.mjs, so
    // agreement between the two is evidence rather than a tautology.
    const pairs = [];
    for (let i = 0; i < ELEMENTS.length; i += 1) {
      for (let j = i + 1; j < ELEMENTS.length; j += 1) {
        pairs.push({ a: ELEMENTS[i], b: ELEMENTS[j], ratio: contrast(ELEMENTS[i].hex, ELEMENTS[j].hex) });
      }
    }
    pairs.sort((x, y) => x.ratio - y.ratio);
    expect(pairs).toHaveLength(21);
    expect(pairs[0].a.id).toBe('amber');
    expect(pairs[0].b.id).toBe('aqua');
    expect(pairs[0].ratio.toFixed(2)).toBe('1.10');
    // Two pairs inside the CLASSIC five are the closest, so this was never a
    // SEVEN problem. Round 2 named INDIGO/VIOLET as the weakest pair; it is
    // THIRD, and round 4's test comment said fourth about its own sorted data.
    expect(spherePairs().map((pair) => pair.key)).toEqual(pairs.map((pair) => `${pair.a.id}|${pair.b.id}`));
  });

  /**
   * The round-4 defect this block exists for.
   *
   * §6.1's list was four hand-typed pairs. Every ratio in it was right and the
   * SET was wrong: it omitted AMBER↔ROSE (1.2470, third — a 0.002 gap from
   * VIOLET↔INDIGO) and published the fifth-closest instead. The old test sorted
   * all 21 pairs and then asserted `pairs[0]` plus four `toContain` substring
   * checks, so it validated every number and never the claim.
   *
   * These tests assert the CLAIM: the published rows are the k closest pairs,
   * in order, with the ratios this module computes.
   */
  describe('§6.1 publishes the closest pairs, as a set and in order', () => {
    const documented = documentedClosestPairs();

    it('is generated from the module rather than typed', () => {
      expect(DESIGN).toContain('tools/lib/palette.mjs');
      expect(documented).toHaveLength(PUBLISHED_CLOSEST_PAIRS);
      // The whole fenced block must be byte-identical to the generator's output.
      const start = DESIGN.indexOf('<!-- palette:closest-pairs:start -->');
      const end = DESIGN.indexOf('<!-- palette:closest-pairs:end -->');
      const block = DESIGN.slice(start + '<!-- palette:closest-pairs:start -->'.length, end).trim();
      expect(block).toBe(closestPairsMarkdown());
    });

    it('names exactly the k closest pairs, in ascending order', () => {
      const expected = closestPairs().map((pair) => `${pair.a.name}↔${pair.b.name}`);
      expect(documented.map((row) => row.pair)).toEqual(expected);
      // And nothing closer than the last published row is left out: the 6th
      // pair must be strictly worse than the 5th, or the list is arbitrary.
      const all = spherePairs();
      expect(all[PUBLISHED_CLOSEST_PAIRS].ratio).toBeGreaterThan(all[PUBLISHED_CLOSEST_PAIRS - 1].ratio);
    });

    it('quotes every ratio correctly', () => {
      closestPairs().forEach((pair, index) => {
        expect(documented[index].ratio, documented[index].pair).toBe(ratioText(pair.ratio));
      });
    });

    it('includes AMBER↔ROSE, the pair the hand-typed list dropped', () => {
      expect(documented.map((row) => row.pair)).toContain('AMBER↔ROSE');
      const amberRose = spherePairs().find((pair) => pair.key === 'amber|rose');
      const violetIndigo = spherePairs().find((pair) => pair.key === 'violet|indigo');
      // Third and effectively tied with the pair round 4 did name.
      expect(amberRose.ratio).toBeGreaterThan(violetIndigo.ratio);
      expect(amberRose.ratio - violetIndigo.ratio).toBeLessThan(0.01);
      // And §15's remedy must send the validation at it, since nothing else has.
      const open4 = DESIGN.slice(DESIGN.indexOf('4. **SEVEN colour separation'));
      expect(open4).toMatch(/start\s+with AMBER↔ROSE/u);
    });

    it('agrees with the independent bound this file computes', () => {
      expect(luminanceSpan()).toBeCloseTo(1.05 / (FLOOR * (luminance(VOID) + 0.05)), 10);
      expect(bestAchievableSeparation(ELEMENTS.length)).toBeCloseTo(1.284, 2);
      // Every published pair sits below the bound; that is the whole argument.
      for (const pair of closestPairs()) {
        expect(pair.ratio, `${pair.key}`).toBeLessThan(bestAchievableSeparation(ELEMENTS.length) * 1.1);
      }
    });
  });

  it('the withdrawn remedies really did make both pairs worse', () => {
    const byId = Object.fromEntries(ELEMENTS.map((element) => [element.id, element.hex]));
    expect(contrast('#3D8BFF', byId.violet)).toBeLessThan(contrast(byId.indigo, byId.violet));
    expect(contrast('#FF6FB0', byId.coral)).toBeLessThan(contrast(byId.rose, byId.coral));
    // They may be named where they are withdrawn; they may not be prescribed.
    expect(DESIGN).toMatch(/colour remedy is withdrawn/u);
    expect(DESIGN).not.toMatch(/move ROSE toward/u);
    // And they are not in the shipped palette.
    for (const element of ELEMENTS) {
      expect(element.hex).not.toBe('#3D8BFF');
      expect(element.hex).not.toBe('#FF6FB0');
    }
  });

  it('the document commits to the glyph as the guaranteed channel', () => {
    expect(DESIGN).toMatch(/the glyph is the\s+colour-blind channel/u);
    // Every element must carry a distinct glyph for that to be true.
    const glyphs = new Set(ELEMENTS.map((element) => element.glyph));
    expect(glyphs.size).toBe(ELEMENTS.length);
    for (const element of ELEMENTS) expect(DESIGN, element.glyph).toContain(element.glyph);
  });
});
